all: selectionSort palindrome

selectionSort: selectionsort.cpp headers.hpp functions.cpp
	g++ -std=c++11 -Wall selectionSort.cpp -o selectionSort

palindrome: palindrome.cpp
	g++ -std=c++11 -Wall palindrome.cpp -o palindrome

clean:
	rm selectionSort palindrome
